name: Deploy Usinelog Project

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via Jump Host
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      # Copier la clé privée sur le bastion (jump host)
      - name: Copy private key to jump host
        run: |
          # Copie la clé privée dans un fichier temporaire
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa_tmp
          chmod 600 id_rsa_tmp

          # Copie vers le bastion
          scp -o StrictHostKeyChecking=no id_rsa_tmp \
            ${{ secrets.JUMP_HOST_USER }}@${{ secrets.JUMP_HOST_IP }}:/home/${{ secrets.JUMP_HOST_USER }}/id_rsa

          # Nettoyage
          rm id_rsa_tmp

      # Ajuster permissions sur le jump host
      - name: Fix permissions on private key in jump host
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.JUMP_HOST_USER }}@${{ secrets.JUMP_HOST_IP }} \
            "chmod 600 /home/${{ secrets.JUMP_HOST_USER }}/id_rsa"

      # Tester la connexion SSH depuis bastion -> VM APP
      - name: Test SSH connection from jump host to APP VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.JUMP_HOST_USER }}@${{ secrets.JUMP_HOST_IP }} << EOF
            ssh -i /home/${{ secrets.JUMP_HOST_USER }}/id_rsa \
              -o StrictHostKeyChecking=no azureuser@10.2.0.10 "echo '✅ Connexion réussie depuis le jump host vers la VM APP !'"
          EOF
