name: Provisionnement et déploiement des Stack via Ansible

on:
  workflow_dispatch:

jobs:
  deploy:
    name: SSH & Run Ansible Playbook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Terraform 
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} '
          cd /home/azureuser/terraform
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve
          '
        
            
      - name: Deploy Ansible Playbook on Remote Host
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} '
            cd /home/azureuser/ansible/application
            sudo ansible-playbook -i ../inventory deploy_application.yml
          '
      - name: Deploy Ansible Playbook on Remote Host
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} '
            cd /home/azureuser/ansible/monitoring
            sudo ansible-playbook -i ../inventory deploystack.yml
          '
